name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to GitHub Pages
        run: |
          serverless deploy
          mkdir -p $GITHUB_WORKSPACE/docs
          cp -R .serverless $GITHUB_WORKSPACE/docs/.serverless
          cp serverless.yml $GITHUB_WORKSPACE/docs/serverless.yml
          cp login.js $GITHUB_WORKSPACE/docs/login.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
